<a href="https://colab.research.google.com/github/sabshaik27/Machine-Learning/blob/main/Model_Selection_or_Cross_Validation/CV_or_MS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.utils import resample

data = [1, 2, 3, 4, 5, 6]

outputBoot_resample = resample(data, replace=True, n_samples=4, random_state=1)

print('Bootstrap Sample: %s' % outputBoot_resample)

result = [x for x in data if x not in outputBoot_resample]

print('OOB Sample: %s' % result)

Bootstrap Sample: [6, 4, 5, 1]
OOB Sample: [2, 3]


In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

In [4]:
iris = datasets.load_iris()
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0)

In [6]:
X_train.shape, y_train.shape

((90, 4), (90,))

In [7]:
X_test.shape, y_test.shape

((60, 4), (60,))

In [8]:
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf.score(X_test, y_test)

0.9666666666666667

In [10]:
#Leave-One-Out

import numpy as np
#from sklearn.cross_validation import LeaveOneOut
from sklearn.model_selection import LeaveOneOut

X = np.array([[0, 0], [1, 1], [2, 2], [3, 3]])

Y = np.array([0, 1, 0, 1])

loo = LeaveOneOut(len(Y))
print(loo)

for train, test in loo:
    print(train, test)

TypeError: LeaveOneOut() takes no arguments

In [11]:
import numpy as np
from sklearn.model_selection import LeaveOneOut

X = np.array([[0, 0], [1, 1], [2, 2], [3, 3]])
Y = np.array([0, 1, 0, 1])

# Initialize LeaveOneOut without arguments
loo = LeaveOneOut()

# Print number of splits
print(f"Number of splits: {loo.get_n_splits(X)}")

# Iterate through splits
for train_idx, test_idx in loo.split(X):
    print("Train:", train_idx, "Test:", test_idx)
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = Y[train_idx], Y[test_idx]
    # Here you can fit your model on X_train, y_train


Number of splits: 4
Train: [1 2 3] Test: [0]
Train: [0 2 3] Test: [1]
Train: [0 1 3] Test: [2]
Train: [0 1 2] Test: [3]


In [12]:
#Leave-P-Out

from sklearn.cross_validation import LeavePOut
X = [[0, 0], [1, 1], [2, 2], [3, 3]]

Y = [0, 1, 0, 1]

lpo = LeavePOut(len(Y), 2)
print(lpo)

for train, test in lpo:
    print(train, test)

ModuleNotFoundError: No module named 'sklearn.cross_validation'

In [13]:
import numpy as np
from sklearn.model_selection import LeavePOut

# Data
X = np.array([[0, 0], [1, 1], [2, 2], [3, 3]])
Y = np.array([0, 1, 0, 1])

# Leave-P-Out with p=2
lpo = LeavePOut(p=2)
print(lpo)  # LeavePOut(p=2)

# Number of splits = C(n, p)
print("Number of splits:", lpo.get_n_splits(X))

# Iterate over splits
for train_idx, test_idx in lpo.split(X, Y):
    print("Train idx:", train_idx, " Test idx:", test_idx)
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = Y[train_idx], Y[test_idx]
    # Fit and evaluate your model here


LeavePOut(p=2)
Number of splits: 6
Train idx: [2 3]  Test idx: [0 1]
Train idx: [1 3]  Test idx: [0 2]
Train idx: [1 2]  Test idx: [0 3]
Train idx: [0 3]  Test idx: [1 2]
Train idx: [0 2]  Test idx: [1 3]
Train idx: [0 1]  Test idx: [2 3]


In [14]:
#KFold

import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=2)
kf.get_n_splits(X)

print(kf)

for train_index, test_index in kf.split(X):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]

KFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [2 3] TEST: [0 1]
TRAIN: [0 1] TEST: [2 3]


In [15]:
#StratifiedKFold

import numpy as np
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 1, 1])
skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(X, y)

print(skf)

for train_index, test_index in skf.split(X, y):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]

StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [1 3] TEST: [0 2]
TRAIN: [0 2] TEST: [1 3]


In [16]:
#TimeSeriesSplit


from sklearn.model_selection import TimeSeriesSplit

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])

tscv = TimeSeriesSplit(n_splits=3,max_train_size= None)
print(tscv)

for train, test in tscv.split(X):
    print("%s %s" % (train, test))

TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None)
[0 1 2] [3]
[0 1 2 3] [4]
[0 1 2 3 4] [5]


In [18]:
'''
 Leave-One-Label-Out - LOLO¶
LeaveOneLabelOut (LOLO) is a cross-validation scheme which holds out the samples according to a third-party provided label.
 This label information can be used to encode arbitrary domain specific stratifications of the samples as integers.

Each training set is thus constituted by all the samples except the ones related to a specific label.

For example, in the cases of multiple experiments, LOLO can be used to create a cross-validation based on the
different experiments: we create a training set using the samples of all the experiments except one:
'''

from sklearn.model_selection import LeaveOneLabelOut
X = [[0, 0], [1, 1], [2, 2], [3, 3]]

Y = [0, 1, 0, 1]

labels = [1, 1, 2, 2]

lolo = LeaveOneLabelOut(labels)
print(lolo)

for train, test in lolo:
    print(train, test)



ImportError: cannot import name 'LeaveOneLabelOut' from 'sklearn.model_selection' (/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/__init__.py)

In [19]:
import numpy as np
from sklearn.model_selection import LeaveOneGroupOut

# Data
X = np.array([[0, 0], [1, 1], [2, 2], [3, 3]])
y = np.array([0, 1, 0, 1])
groups = np.array([1, 1, 2, 2])  # formerly "labels"

logo = LeaveOneGroupOut()
print(logo)  # LeaveOneGroupOut()

# Number of splits equals number of unique groups
print("Number of splits:", logo.get_n_splits(X, y, groups))

# Iterate over splits
for train_idx, test_idx in logo.split(X, y, groups):
    print("Train:", train_idx, " Test:", test_idx)
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    # Fit/evaluate your model here


LeaveOneGroupOut()
Number of splits: 2
Train: [2 3]  Test: [0 1]
Train: [0 1]  Test: [2 3]


In [20]:
'''
Leave-P-Label-Out
LeavePLabelOut is similar as Leave-One-Label-Out, but removes samples related to P labels for each
training/test set.

'''
from sklearn.cross_validation import LeavePLabelOut
X = [[0., 0.], [1., 1.], [-1., -1.],
     [2., 2.], [3., 3.], [4., 4.]]

Y = [0, 1, 0, 1, 0, 1]

labels = [1, 1, 2, 2, 3, 3]

lplo = LeavePLabelOut(labels, 2)
print(lplo)

for train, test in lplo:
    print(train, test)



ModuleNotFoundError: No module named 'sklearn.cross_validation'

In [21]:
import numpy as np
from sklearn.model_selection import LeavePGroupsOut

# Data
X = np.array([[0., 0.], [1., 1.], [-1., -1.],
              [2., 2.], [3., 3.], [4., 4.]])
y = np.array([0, 1, 0, 1, 0, 1])
groups = np.array([1, 1, 2, 2, 3, 3])  # formerly "labels"

# Leave-P-Groups-Out with p = 2 groups
lpgo = LeavePGroupsOut(n_groups=2)
print(lpgo)  # LeavePGroupsOut(n_groups=2)

# Number of splits = combinations of unique groups taken 2 at a time
print("Number of splits:", lpgo.get_n_splits(X, y, groups))

# Iterate over splits
for train_idx, test_idx in lpgo.split(X, y, groups):
    print("Train:", train_idx, " Test:", test_idx)
    # X_train, X_test = X[train_idx], X[test_idx]
    # y_train, y_test = y[train_idx], y[test_idx]
    # Fit/evaluate your model here


LeavePGroupsOut(n_groups=2)
Number of splits: 3
Train: [4 5]  Test: [0 1 2 3]
Train: [2 3]  Test: [0 1 4 5]
Train: [0 1]  Test: [2 3 4 5]


In [22]:
'''
Random permutations cross-validation a.k.a. Shuffle & Split¶
ShuffleSplit

The ShuffleSplit iterator will generate a user defined number of independent train / test dataset splits. Samples are first shuffled and then splitted into a pair of train and test sets.

It is possible to control the randomness for reproducibility of the results by explicitly seeding the random_state pseudo random number generator.

Here is a usage example:

    "Random permutation cross-validator

Yields indices to split data into training and test sets.

Note: contrary to other cross-validation strategies, random splits do not guarantee that all folds will be different, although this is still very likely for sizeable datasets."

'''

import numpy as np
from sklearn.model_selection import ShuffleSplit
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [3, 4], [5, 6]])

y = np.array([1, 2, 1, 2, 1, 2])

rs = ShuffleSplit(n_splits=5, test_size=.25, random_state=0)
rs.get_n_splits(X)

print(rs)

for train_index, test_index in rs.split(X):
   print("TRAIN:", train_index, "TEST:", test_index)

rs = ShuffleSplit(n_splits=5, train_size=0.5, test_size=.25,
                  random_state=0)

for train_index, test_index in rs.split(X):
   print("TRAIN:", train_index, "TEST:", test_index)


ShuffleSplit(n_splits=5, random_state=0, test_size=0.25, train_size=None)
TRAIN: [1 3 0 4] TEST: [5 2]
TRAIN: [4 0 2 5] TEST: [1 3]
TRAIN: [1 2 4 0] TEST: [3 5]
TRAIN: [3 4 1 0] TEST: [5 2]
TRAIN: [3 5 1 0] TEST: [2 4]
TRAIN: [1 3 0] TEST: [5 2]
TRAIN: [4 0 2] TEST: [1 3]
TRAIN: [1 2 4] TEST: [3 5]
TRAIN: [3 4 1] TEST: [5 2]
TRAIN: [3 5 1] TEST: [2 4]


In [23]:
'''

Time Series CV using Python very basic Example to understand the working ...
'''

import numpy as np
from sklearn.model_selection import TimeSeriesSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])

y = np.array([1, 2, 3, 4, 5, 6])

tscv = TimeSeriesSplit(n_splits=5)
print(tscv)

for train_index, test_index in tscv.split(X):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]


TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None)
TRAIN: [0] TEST: [1]
TRAIN: [0 1] TEST: [2]
TRAIN: [0 1 2] TEST: [3]
TRAIN: [0 1 2 3] TEST: [4]
TRAIN: [0 1 2 3 4] TEST: [5]
