<a href="https://colab.research.google.com/github/sabshaik27/Machine-Learning/blob/main/Data_preprocessing/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import the libraries

import numpy as py

import matplotlib.pyplot as plt

import pandas as pd

In [ ]:
#Import the data set from Desktop

dataset = pd.read_csv('DataSet.csv')

X=dataset.iloc[:,:-1].values
XX=dataset.iloc[:,:-1].values
XXX=dataset.iloc[:,:-1].values
y=dataset.iloc[:,3].values

print(X)
print(y)

[['Karachi' 42.0 78000.0]
 ['Lahore' 32.0 48000.0]
 ['Karachi' 36.0 60000.0]
 ['Multan' 41.0 68000.0]
 ['Lahore' 42.0 nan]
 ['Multan' 43.0 59000.0]
 ['Karachi' nan 59000.0]
 ['Lahore' 44.0 79000.0]
 ['Multan' 52.0 99000.0]
 ['Lahore' 32.0 69000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
#MEAN
import numpy as np
from sklearn.impute import SimpleImputer

# Choose the columns to impute (here: columns 1 and 2)
cols = slice(1, 3)

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:, cols] = imputer.fit_transform(X[:, cols])

In [ ]:
print(X)

[['Karachi' 42.0 78000.0]
 ['Lahore' 32.0 48000.0]
 ['Karachi' 36.0 60000.0]
 ['Multan' 41.0 68000.0]
 ['Lahore' 42.0 68777.77777777778]
 ['Multan' 43.0 59000.0]
 ['Karachi' 40.44444444444444 59000.0]
 ['Lahore' 44.0 79000.0]
 ['Multan' 52.0 99000.0]
 ['Lahore' 32.0 69000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
#MEDIAN
import numpy as np
from sklearn.impute import SimpleImputer

# Choose the columns to impute (here: columns 1 and 2)
cols = slice(1, 3)

imputer = SimpleImputer(missing_values=np.nan, strategy='median')
XX[:, cols] = imputer.fit_transform(XX[:, cols])

print(XX)

[['Karachi' 42.0 78000.0]
 ['Lahore' 32.0 48000.0]
 ['Karachi' 36.0 60000.0]
 ['Multan' 41.0 68000.0]
 ['Lahore' 42.0 68000.0]
 ['Multan' 43.0 59000.0]
 ['Karachi' 42.0 59000.0]
 ['Lahore' 44.0 79000.0]
 ['Multan' 52.0 99000.0]
 ['Lahore' 32.0 69000.0]]


In [ ]:
#MODE
import numpy as np
from sklearn.impute import SimpleImputer

# Choose the columns to impute (here: columns 1 and 2)
cols = slice(1, 3)

imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
XXX[:, cols] = imputer.fit_transform(XXX[:, cols])

print(XXX)

[['Karachi' 42.0 78000.0]
 ['Lahore' 32.0 48000.0]
 ['Karachi' 36.0 60000.0]
 ['Multan' 41.0 68000.0]
 ['Lahore' 42.0 59000.0]
 ['Multan' 43.0 59000.0]
 ['Karachi' 32.0 59000.0]
 ['Lahore' 44.0 79000.0]
 ['Multan' 52.0 99000.0]
 ['Lahore' 32.0 69000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],
    remainder='passthrough'
)

X = ct.fit_transform(X)
X = np.array(X)


In [ ]:
#Training and Testing Data (divide the data into two part)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.2, random_state=0)

In [ ]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[0.0 1.0 0.0 42.0 68777.77777777778]
 [0.0 1.0 0.0 32.0 69000.0]
 [0.0 1.0 0.0 32.0 48000.0]
 [1.0 0.0 0.0 40.44444444444444 59000.0]
 [0.0 1.0 0.0 44.0 79000.0]
 [0.0 0.0 1.0 41.0 68000.0]
 [1.0 0.0 0.0 42.0 78000.0]
 [0.0 0.0 1.0 43.0 59000.0]]
[[1.0 0.0 0.0 36.0 60000.0]
 [0.0 0.0 1.0 52.0 99000.0]]
['Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes']
['No' 'No']


In [ ]:
#Standard and fit the data for better predication

from sklearn.preprocessing import StandardScaler

sc_X=StandardScaler()

X_test=sc_X.fit_transform(X_test)


X_train=sc_X.fit_transform(X_train)

print(X_train)
print(X_test)


[[-0.57735027  1.         -0.57735027  0.54554305  0.2758114 ]
 [-0.57735027  1.         -0.57735027 -1.68622397  0.29867659]
 [-0.57735027  1.         -0.57735027 -1.68622397 -1.86208422]
 [ 1.73205081 -1.         -0.57735027  0.19837929 -0.73025713]
 [-0.57735027  1.         -0.57735027  0.99189645  1.32761031]
 [-0.57735027 -1.          1.73205081  0.32236635  0.19578322]
 [ 1.73205081 -1.         -0.57735027  0.54554305  1.22471694]
 [-0.57735027 -1.          1.73205081  0.76871975 -0.73025713]]
[[ 1.  0. -1. -1. -1.]
 [-1.  0.  1.  1.  1.]]
